return {
    "stevearc/aerial.nvim",
    event = "VeryLazy",
    dependencies = {
        "nvim-treesitter/nvim-treesitter",
        "nvim-tree/nvim-web-devicons",
    },
    config = function()
        require("aerial").setup({
            attach_mode = "global",
            close_on_select = true,
            layout = {
                min_width = 30,
                default_direction = "prefer_right",
                show_guides = true,
                icons = {
                    File = "󰈙 ",
                    Module = " ",
                    Namespace = "󰌗 ",
                    Package = " ",
                    Class = "󰌗 ",
                    Method = "󰆧 ",
                    Property = " ",
                    Field = " ",
                    Constructor = " ",
                    Enum = "󰕘 ",
                    Interface = "󰕘 ",
                    Function = "󰊕 ",
                    Variable = "󰆧 ",
                    Constant = "󰏿 ",
                    String = "󰀬 ",
                    Number = "󰎠 ",
                    Boolean = "◩ ",
                    Array = "󰅪 ",
                    Object = "󰅩 ",
                    Key = "󰌋 ",
                    Null = "󰟢 ",
                    EnumMember = " ",
                    Struct = "󰌗 ",
                    Event = " ",
                    Operator = "󰆕 ",
                    TypeParameter = "󰊄 ",
                },
                filter_kind = {
                    "Class",
                    "Constructor",
                    "Enum",
                    "Function",
                    "Interface",
                    "Module",
                    "Method",
                    "Struct",
                    "Variable",
                    "Constant",
                    "Boolean",
                    "Array",
                    "Object",
                },
                highlight_closest = true,
                highlight_on_hover = true,
                close_automatic_events = { "unfocus", "switch_buffer", "unsupported" },
            },
        })
    end,
    keys = {
        {
            "<leader>a",
            "<cmd>AerialToggle<CR>",
            desc = "Toggle Aerial (Symbol Outline)",
        },
    },
}
