return{
    { import = "theocratickiwi.plugins.nvim-cmp"            },
    { import = "theocratickiwi.plugins.none-ls"             },
    { import = "theocratickiwi.plugins.vim-tmux-navigator"  },
	{ import = "theocratickiwi.plugins.lsp"		            },
	{ import = "theocratickiwi.plugins.vim-fugitive"        },
	{ import = "theocratickiwi.plugins.undotree"	        },
	{ import = "theocratickiwi.plugins.nvim-tree" 	        },
	{ import = "theocratickiwi.plugins.telescope" 	        },
	{ import = "theocratickiwi.plugins.harpoon2"	        },
	{ import = "theocratickiwi.plugins.lualine"	            },
	{ import = "theocratickiwi.plugins.treesitter" 	        },
	{ import = "theocratickiwi.plugins.catppuccin" 	        },
    { import = "theocratickiwi.plugins.alpha-nvim"          },
}
