return{
    { import = "theocratickiwi.plugins.nvim-dap"            },
    { import = "theocratickiwi.plugins.none-ls"             },
    { import = "theocratickiwi.plugins.vim-tmux-navigator"  },
	{ import = "theocratickiwi.plugins.lsp"		            },
    { import = "theocratickiwi.plugins.nvim-cmp"            },
	{ import = "theocratickiwi.plugins.vim-fugitive"        },
	{ import = "theocratickiwi.plugins.undotree"	        },
	{ import = "theocratickiwi.plugins.neo-tree"	        },
	{ import = "theocratickiwi.plugins.lualine"	            },
	{ import = "theocratickiwi.plugins.treesitter" 	        },
	{ import = "theocratickiwi.plugins.colorscheme" 	    },
    { import = "theocratickiwi.plugins.alpha-nvim"          },
    { import = "theocratickiwi.plugins.blade"               },
    { import = "theocratickiwi.plugins.colorizer"           },
    { import = "theocratickiwi.plugins.comment"             },
    { import = "theocratickiwi.plugins.image"               },
    { import = "theocratickiwi.plugins.molten"              },
    { import = "theocratickiwi.plugins.quarto"              },
    { import = "theocratickiwi.plugins.jupytext"            },
    { import = "theocratickiwi.plugins.codecompanion"       },
    { import = "theocratickiwi.plugins.column-vert"         },
    { import = "theocratickiwi.plugins.snacks"              },
    { import = "theocratickiwi.plugins.aerial"              },
}
